Models/Guestbooks.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guestbooks
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Reply { get; set; }
        public Nullable<System.DateTime> ReplyTime { get; set; }
    }
}

ViewModels/GuestbooksView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MVC2.Models;


namespace MVC2.ViewModels
{
    public class GuestbooksView
    {
        public List<Guestbooks> DataList { get; set; }



    }
}

Controllers/GuestbookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC2.Service;
using MVC2.ViewModels;
using MVC2.Models;

namespace MVC2.Controllers
{
    public class GuestbookController : Controller
    {

        GuestbookDBService guestbookService = new GuestbookDBService();

        // GET: Guestbook
        public ActionResult Index()
        {
            GuestbooksView Data = new GuestbooksView();
            Data.DataList = guestbookService.GetDataList();
            return View(Data);
        }

        public ActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult Add([Bind(Include ="Name,Content")] Guestbooks Data)
        {
            guestbookService.InsertGuestbooks(Data);            
            return RedirectToAction("Index");
        }

        public ActionResult Edit (int Id)
        {
            Guestbooks Data = guestbookService.GetDataById(Id);
            return View(Data);
        }

        [HttpPost]
        public ActionResult Edit(int Id, [Bind(Include = "Name,Contetn")] Guestbooks UpdateData)
        {
            if (guestbookService.CheckUpdate(Id))
            {
                UpdateData.Id = Id;
                guestbookService.UpdateGuesbook(UpdateData);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult Reply(int Id)
        {
            Guestbooks Data = guestbookService.GetDataById(Id);
            return View(Data);
        }

        [HttpPost]
        public ActionResult Reply (int Id,[Bind(Include ="Reply,ReplyTime")] Guestbooks ReplyData)
        {
            if(guestbookService.CheckUpdate(Id))
            {
                ReplyData.Id = Id;
                guestbookService.RelpyGuestbook(ReplyData);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
    }
}

Views/Guestbook/Create.cshtml
@model MVC2.Models.Guestbooks


@using (Html.BeginForm("Add","Guestbook")) 
{
    <h3>新增留言</h3>
    <table>
        <tr>
            <td>
                @Html.LabelFor(model=> model.Name)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Name)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.Content)
            </td>
            <td>
                @Html.TextBoxFor(model => model.Content)
            </td>
        </tr>
    </table>
    <input type="submit" value="新增留言" />
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Guestbook/Edit.cshtml
@model MVC2.Models.Guestbooks

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
   <h3>修改留言</h3>
   <table>
       <tr>
           <td>
               @Html.LabelFor(p=>p.Name)
           </td>
           <td>
               @Html.TextBoxFor(p => p.Name)
           </td>
       </tr>
       <tr>
           <td>
               @Html.LabelFor(p => p.Content)
           </td>
           <td>
               @Html.TextBoxFor(p => p.Content)
           </td>
       </tr>
   </table>

    if (Model.ReplyTime == null)
    {
        <input type="submit" value="修改留言" />
    }
    else
    {
        <text>此留言回覆過無法修改，請</text>
        @Html.ActionLink("返回列表","Index")
    }

}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Guestbook/Index.cshtml
@model MVC2.ViewModels.GuestbooksView

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@Html.Action("Create","Guestbook")


@if (!Model.DataList.Count.Equals(0))
{
    foreach (var Item in Model.DataList)
    {
        <tr>
            <td>
                @Html.LabelFor(model => model.DataList[0].Name)
            </td>
            <td>
                @Item.Name
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.DataList[0].CreateTime)
            </td>
            <td>
                @Item.CreateTime
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.DataList[0].Content)
            </td>
            <td colspan="3">
                @Item.Content
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.DataList[0].Reply)
            </td>
            <td colspan="3">
                @Item.Reply
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.DataList[0].ReplyTime)
            </td>
            <td >
                @Item.ReplyTime
            </td>
           
        </tr>

    }
}
else
{
 <tr>
     <td colspan="4">
         資料庫無資料
     </td>
 </tr>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Guestbook/Reply.cshtml
@model MVC2.Models.Guestbooks

@{
    ViewBag.Title = "Reply";
}

<h2>Reply</h2>


@using (Html.BeginForm())
{
    <h3>回覆留言</h3>
    <table>
        <tr>
            <td>
                @Html.LabelFor(p => p.Name)
            </td>
            <td>
                @Html.LabelFor(p => p.Name)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(p => p.Content)
            </td>
            <td>
                @Html.LabelFor(p => p.Content)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(p => p.Reply)
            </td>
            <td>
                @Html.TextBoxFor(p => p.Reply)
            </td>
        </tr>

    </table>

    if (Model.ReplyTime == null)
    {
        <input type="submit" value="回覆留言" />
    }
    else
    {
        <text>此留言已回覆無法修改，請</text>
        @Html.ActionLink("返回列表", "Index")
    }
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}